# Generated by Django 5.2.7 on 2025-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
